# Dependencies
highlighter:    pygments
markdown:       redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]


# Setup
title:          'TMZ'
tagline:        'Documentation for TMZ apps and projects.'
description:    ''
baseurl:        /
future:         true
paginate:       30
theme:          'theme-base-tmz'


# Permalinks
permalink:      pretty


# Exclude non-site files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
